name: Monitor-M4-Liquidacion

on:
  schedule:
    - cron: '*/30 * * * *' # Esto lo corre cada 30 minutos, las 24 horas.
  workflow_dispatch:      # Este comando nos permite probarlo a mano con un botón.

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo del repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar libreria Requests
        run: pip install requests

      - name: Ejecutar el script de monitoreo
        env:
          # Aca vinculamos tus "Secrets" con el script de Python
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor.py
